version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - "4300:4300"
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
  db:
    image: postgres
    env_file:
      - .env
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080