package errs

import "errors"

var (
	ErrUsernameExists       = errors.New("username already exists")
	ErrInvalidPassword      = errors.New("invalid password")
	ErrInvalidToken         = errors.New("invalid token")
	ErrTokenExpired         = errors.New("token expired")
	ErrSessionNotFound      = errors.New("session not found")
	ErrSessionExpired       = errors.New("session expired")
	ErrSessionIPMismatch    = errors.New("session IP mismatch")
	ErrSessionUAMismatch    = errors.New("session User-Agent mismatch")
	ErrNotFound             = errors.New("not found")
	ErrGameExists           = errors.New("game already exists")
	ErrGameNotFound         = errors.New("game not found")
	ErrMatchNotFound        = errors.New("match not found")
	ErrPlayerAlreadyInMatch = errors.New("player already in match")
	ErrMatchFull            = errors.New("match is full")
	ErrMatchNotJoinable     = errors.New("match is not joinable")
	ErrMatchNotLeavable     = errors.New("match is not leavable")
	ErrMatchNotStartable    = errors.New("match is not startable")
	ErrMatchAlreadyFinished = errors.New("match is already finished")
	ErrMatchStarted         = errors.New("match has already started")
	ErrMatchNotStarted      = errors.New("match has not started yet")
	ErrMatchNotFinished     = errors.New("match is not finished")
	ErrInvalidChoice        = errors.New("invalid choice")
	ErrPlayerNotFound       = errors.New("player not found in match")
	ErrNotPlayerTurn        = errors.New("it's not your turn")
	ErrInvalidRole          = errors.New("invalid player role")
	ErrInsufficientBalance  = errors.New("insufficient balance")
	ErrMatchMinPlayers      = errors.New("match has not enough players")
	ErrMatchMaxPlayers      = errors.New("match has too many players")
)
